add docker
Asteises/ewm-diplom pull request #1
Opened 2022-11-29 12:07 UTC by Asteises

2022-11-30 23:34 UTC, alexache requested changes

2022-11-30 23:34 UTC, alexache commented on docker-compose.yml
> +      - ewm-db
Еще зависит от stats-server

2022-11-30 23:34 UTC, alexache commented on main-service/pom.xml
> +            <version>2.0.1.Final</version>
Версии должны быть указаны только в родительском модуле через dependencyManagement

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/model/Category.java
> +@EqualsAndHashCode
Этой аннотации не должно быть на модели

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/model/dto/CategoryDto.java
> +@Validated
Мне кажется, эта аннотация лишняя

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        checkNameCategory(categoryDto.getName());
А если при апдейте не меняется имя? (да, ложный вызов, но все же), нужно еще  id сверить

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        category.setId(categoryDto.getId());
Это явно лишнее

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        List<Category> categories = categoryStorage.findAll(PageRequest.of(from / size, size)).stream().collect(Collectors.toList());
Зачем сначала делать collect() а потом снова создавать стрим на нем?

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/model/Compilation.java
> +    private String title;
Хорошо бы здесь же и иметь список событий через аннотации @JoinColumn и @ManyToMany

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/model/CompilationEvent.java
> +public class CompilationEvent {
Лишний класс все же

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        for (Compilation compilation : compilations) {
А отчего бы на стриме выше просто не вызвать map(CompilationMapper::fromCompToCompDto)? Для чего новые запросы к базе в цикле?

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        for (CompilationEvent compilationEvent : compilationEvents) {
Это должно исправиться, если сделать @JoinColumn/@ManyToMany

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        compilationStorage.save(compilation);
Лучше использовать результат от вызова метода save и конвертировать его в дто

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/model/Event.java
> +    private Long confirmedRequests;
Лучше не хранить это на событии, а считать отдельно

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/model/Event.java
> +    private Double locationLat;
А для чего тогда модель Location?

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            EventFullDto eventFullDto = getPublicEventById(event.getId());
Не стоит в цикле обращаться к базе данных, это очень плохо

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<EventFullDto> result = eventsIds.stream().map(this::getPublicEventById).collect(Collectors.toList());
Запрос к базе в цикле

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        Event event = checkEventAvailableInDb(eventId);
Для чего повторные запрос к базе?

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/request/service/RequestServiceImpl.java
> +        eventService.checkStatusPublished(event.getId());
Там повторный запрос к базе

2022-11-30 23:34 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/user/model/User.java
> +@EqualsAndHashCode
Этой аннотации не должно быть

2022-11-30 23:34 UTC, alexache commented on stats-service/pom.xml
> +            <version>0.8.1</version>
И здесь не должно быть версий, а в родительском модуле

2022-11-30 23:34 UTC, alexache commented on stats-service/src/main/java/ru/praktikum/statsservice/model/EndpointHit.java
> +@EqualsAndHashCode
Лишняя аннотация

2022-11-30 23:34 UTC, alexache commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            uris = statStorage.findAllByCreatedBetween(currentStart, currentEnd)
Может проще просто сразу собрать и всю статистику, без отдельного запроса по URI?

2022-11-30 23:34 UTC, alexache commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            endpointHits = statStorage.findByUri(uri);
Не должно быть запросов к базе в цикле - нужно написать один запрос по списку URI

2022-11-30 23:34 UTC, alexache commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            if (unique) {
Будет лучше делать это на уровне запроса

2022-12-01 08:16 UTC, Asteises commented on docker-compose.yml
> +      - ewm-db
исправил

2022-12-01 08:24 UTC, Asteises commented on main-service/pom.xml
> +            <version>2.0.1.Final</version>
Я предполагал, что это только для тех зависимостей, которые есть в основном и дочернем помнике... То есть нужно вообще все зависимости с версиями указать в основном помнике, а в дочерних указать только зависимости без версий?

2022-12-01 08:27 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/model/Category.java
> +@EqualsAndHashCode
исправил

2022-12-01 08:51 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/model/dto/CategoryDto.java
> +@Validated
исправил

2022-12-01 08:56 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        checkNameCategory(categoryDto.getName());
Не могу понять. Нам нужно изменить категорию. Пришло Дто с id, мы нашли эту категорию в БД. Потом проверили имя пришедшее в ДТО, чтобы такого имени не было в БД. И вот тогда мы меняем. То есть, с чем еще нужно сверить id, если мы и так по нему искали категорию?

2022-12-01 08:57 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        category.setId(categoryDto.getId());
исправил

2022-12-01 09:15 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/model/Compilation.java
> +    private String title;
исправил

2022-12-01 10:21 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/model/CompilationEvent.java
> +public class CompilationEvent {
исправил

2022-12-01 10:24 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        for (Compilation compilation : compilations) {
исправил

2022-12-01 10:24 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        for (CompilationEvent compilationEvent : compilationEvents) {
исправил

2022-12-01 10:27 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/compilations/service/CompilationServiceImpl.java
> +        compilationStorage.save(compilation);
поправил... там же еще нужно засетить события перед тем как сохранить

2022-12-01 10:57 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/model/Event.java
> +    private Long confirmedRequests;
исправил

2022-12-01 10:57 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/model/Event.java
> +    private Double locationLat;
исправил

2022-12-01 11:25 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            EventFullDto eventFullDto = getPublicEventById(event.getId());
исправил... stream же можно использовать? иначе у меня больше нет вариантов...

2022-12-01 11:26 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<EventFullDto> result = eventsIds.stream().map(this::getPublicEventById).collect(Collectors.toList());
исходя из этого предыдущее тоже неправильно сделано... тогда как нужно?

2022-12-01 11:28 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        Event event = checkEventAvailableInDb(eventId);
не понял, тут же один только запрос...

2022-12-01 11:30 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/request/service/RequestServiceImpl.java
> +        eventService.checkStatusPublished(event.getId());
исправил

2022-12-01 11:30 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/user/model/User.java
> +@EqualsAndHashCode
исправил

2022-12-01 11:30 UTC, Asteises commented on stats-service/src/main/java/ru/praktikum/statsservice/model/EndpointHit.java
> +@EqualsAndHashCode
исправил

2022-12-02 06:46 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        checkNameCategory(categoryDto.getName());
было допустим  id=1, name=test пришел апдейт id=1, name=test. Ты проверил, что есть такая категория с id=1: а затем у тебя упадет проверка на уникальность имени потому что name=test  уже есть  у этой же записи

2022-12-02 06:47 UTC, alexache commented on main-service/pom.xml
> +            <version>2.0.1.Final</version>
Именно так - все зависимости в родительском помнике

2022-12-02 06:49 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            EventFullDto eventFullDto = getPublicEventById(event.getId());
Нет, нельзя. Стрим - этот тот же цикл по существу

2022-12-02 06:50 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<EventFullDto> result = eventsIds.stream().map(this::getPublicEventById).collect(Collectors.toList());
запрос к базе по списку событий одним запросом

2022-12-02 06:50 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        Event event = checkEventAvailableInDb(eventId);
checkStatusPublished вызывается в другом методе, в которые событие уже бралось из базы по айди

2022-12-02 23:21 UTC, alexache requested changes

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<IdViewsPair> idViewsPairs = getViewsByEventsId(events.stream()
Почему бы из этого не сделать обычную мапу id -> количество просмотров, тогда и работать будет заметно быстрее

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +                if (eventShortDto.getId().equals(idViewsPair.getId())) {
Потому что это называется квадратичный алгоритм (обход массива обходя другой массив), что есть очень плохой знак. Если же просмотры зранятся в мапе, то будет нормальный алгоритм

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        for (EventFullDto eventFullDto : result) {
Комментарий выше применим и здесь

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            ArrayList<LinkedHashMap<Object, Object>> listFromObject = (ArrayList<LinkedHashMap<Object, Object>>) response.getBody();
Попробуй ближе к концу работы отойти от этого грязного хака

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<IdViewsPair> idViewsPairs = getViewsByEventsId(List.of(eventId));
Вот там выше причина моего коммента про checkStatusPublished, где повторно делается запрос по айди события

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
>          log.info("Выводим все публичные события : result={}", result);
А где разные виды сортировок, исходя из значения sort?

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> -                .map(this::setViewsAndConfReqToEventShortDto)
А как теперь выставляется количество подтвержденных заявок?

2022-12-02 23:21 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
>      */
Это можно сразу вызывать не findAllByEvent_IdAndStatus а countByEvent_IdAndStatus

2022-12-03 11:08 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
>      */
исправил

2022-12-03 11:16 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<IdViewsPair> idViewsPairs = getViewsByEventsId(events.stream()
исправил

2022-12-03 11:32 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +                if (eventShortDto.getId().equals(idViewsPair.getId())) {
Исправил. Хочется сделать через stream, попробовал разные варианты, но не получилось...

2022-12-03 12:40 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        for (EventFullDto eventFullDto : result) {
Исправил

2022-12-03 12:41 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            ArrayList<LinkedHashMap<Object, Object>> listFromObject = (ArrayList<LinkedHashMap<Object, Object>>) response.getBody();
Я бы с удовольствием, но не знаю как...

2022-12-03 12:41 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<IdViewsPair> idViewsPairs = getViewsByEventsId(List.of(eventId));
Исправил

2022-12-03 12:55 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
>          log.info("Выводим все публичные события : result={}", result);
Исправил

2022-12-03 12:55 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> -                .map(this::setViewsAndConfReqToEventShortDto)
Исправил

2022-12-03 13:02 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        checkNameCategory(categoryDto.getName());
исправил

2022-12-03 13:04 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/category/service/CategoryServiceImpl.java
> +        List<Category> categories = categoryStorage.findAll(PageRequest.of(from / size, size)).stream().collect(Collectors.toList());
исправил

2022-12-03 13:05 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            EventFullDto eventFullDto = getPublicEventById(event.getId());
исправил

2022-12-03 13:05 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        List<EventFullDto> result = eventsIds.stream().map(this::getPublicEventById).collect(Collectors.toList());
исправил

2022-12-03 13:07 UTC, Asteises commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +        Event event = checkEventAvailableInDb(eventId);
исправил

2022-12-03 13:43 UTC, Asteises commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            uris = statStorage.findAllByCreatedBetween(currentStart, currentEnd)
исправил

2022-12-03 13:43 UTC, Asteises commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            endpointHits = statStorage.findByUri(uri);
исправил

2022-12-03 13:45 UTC, Asteises commented on stats-service/src/main/java/ru/praktikum/statsservice/service/StatServiceImpl.java
> +            if (unique) {
так приходит Boolean, в любом случае будет значение, просто либо произведем сортировку, либо оставим как есть. Или я что-то не понял?

2022-12-03 21:53 UTC, alexache approved these changes

2022-12-03 21:53 UTC, alexache commented on main-service/src/main/java/ru/praktikum/mainservice/event/service/EventServiceImpl.java
> +            result.put(id, requests.stream()
В целом здесь еще можно было бы улучшить: проходить по requests единожды преобразуя чем-то вроде ".collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));" Тогда трешение будешь изящнее

2022-12-05 08:21 UTC, merged